import { serverURL } from "./urls";

export interface Theme {
  title: string;
  beach: string;
  coral: string;
  mint: string;
  ocean: string;
  purple: string;
  rose: string;
  sun: string;
  default?: string;
}

export const backgroundImage_notes: Theme = {
  title: "Notes",
  beach: "/assets/backgrounds/alina_app_notes_wallpaper_beach.png",
  coral: "/assets/backgrounds/alina_app_notes_wallpaper_coral.png",
  mint: "/assets/backgrounds/alina_app_notes_wallpaper_mint.png",
  ocean: "/assets/backgrounds/alina_app_notes_wallpaper_ocean.png",
  purple: "/assets/backgrounds/alina_app_notes_wallpaper.png",
  rose: "/assets/backgrounds/alina_app_notes_wallpaper_rose.png",
  sun: "/assets/backgrounds/alina_app_notes_wallpaper_sun.png",
  default: "/assets/backgrounds/alina_app_notes_wallpaper.png",
};

export const backgroundImage_settings: Theme = {
  title: "Settings",
  beach: "/assets/backgrounds/alina_app_settings_wallpaper_beach.png",
  coral: "/assets/backgrounds/alina_app_settings_wallpaper_coral.png",
  mint: "/assets/backgrounds/alina_app_settings_wallpaper_mint.png",
  ocean: "/assets/backgrounds/alina_app_settings_wallpaper_ocean.png",
  purple: "/assets/backgrounds/alina_app_settings_wallpaper.png",
  rose: "/assets/backgrounds/alina_app_settings_wallpaper_rose.png",
  sun: "/assets/backgrounds/alina_app_settings_wallpaper_sun.png",
  default: "/assets/backgrounds/alina_app_settings_wallpaper.png",
};

export const backgroundImage_reader: Theme = {
  title: "Reader",
  beach: "/assets/backgrounds/hummingbird_reader_beach.png",
  coral: "/assets/backgrounds/hummingbird_reader_coral.png",
  mint: "/assets/backgrounds/hummingbird_reader_mint.png",
  ocean: "/assets/backgrounds/hummingbird_reader_ocean.png",
  purple: "/assets/backgrounds/hummingbird_reader.png",
  rose: "/assets/backgrounds/hummingbird_reader_rose.png",
  sun: "/assets/backgrounds/hummingbird_reader_sun.png",
  default: "/assets/backgrounds/hummingbird_reader.png",
};

export const backgroundImage_listen: Theme = {
  title: "Listen",
  beach: "/assets/backgrounds/I_Love_You_Alina_listen_background_beach.png",
  coral: "/assets/backgrounds/I_Love_You_Alina_listen_background_coral.png",
  mint: "/assets/backgrounds/I_Love_You_Alina_listen_background_mint.png",
  ocean: "/assets/backgrounds/I_Love_You_Alina_listen_background_ocean.png",
  purple: "/assets/backgrounds/I_Love_You_Alina_listen_background.png",
  rose: "/assets/backgrounds/I_Love_You_Alina_listen_background_rose.png",
  sun: "/assets/backgrounds/I_Love_You_Alina_listen_background_sun.png",
  default: "/assets/backgrounds/I_Love_You_Alina_listen_background.png",
};

export const backgroundImage_photos: Theme = {
  title: "Photos",
  beach: "/assets/backgrounds/photos_viewer_beach.png",
  coral: "/assets/backgrounds/photos_viewer_coral.png",
  mint: "/assets/backgrounds/photos_viewer_mint.png",
  ocean: "/assets/backgrounds/photos_viewer_ocean.png",
  purple: "/assets/backgrounds/photos_viewer_purple.png",
  rose: "/assets/backgrounds/photos_viewer_rose.png",
  sun: "/assets/backgrounds/photos_viewer_sun.png",
  default: "/assets/backgrounds/photos_viewer_purple.png",
};

export const book_MyExternalCause: Theme = {
  title: "My External Cause",
  beach: "/assets/backgrounds/my_external_cause_front_cover_beach.png",
  coral: "/assets/backgrounds/my_external_cause_front_cover_coral.png",
  mint: "/assets/backgrounds/my_external_cause_front_cover_mint.png",
  ocean: "/assets/backgrounds/my_external_cause_front_cover_ocean.png",
  purple: "/assets/backgrounds/my_external_cause_front_cover_purple.png",
  rose: "/assets/backgrounds/my_external_cause_front_cover_rose.png",
  sun: "/assets/backgrounds/my_external_cause_front_cover_sun.png",
  default: "/assets/backgrounds/my_external_cause_front_cover_purple.png",
};

export const book_LoveDrunk: Theme = {
  title: "Love Drunk",
  beach: "/assets/backgrounds/Love_Drunk_front_cover_beach.png",
  coral: "/assets/backgrounds/Love_Drunk_front_cover_coral.png",
  mint: "/assets/backgrounds/Love_Drunk_front_cover_mint.png",
  ocean: "/assets/backgrounds/Love_Drunk_front_cover_ocean.png",
  purple: "/assets/backgrounds/Love_Drunk_front_cover_purple.png",
  rose: "/assets/backgrounds/Love_Drunk_front_cover_rose.png",
  sun: "/assets/backgrounds/Love_Drunk_front_cover_sun.png",
  default: "/assets/backgrounds/Love_Drunk_front_cover_purple.png",
};

export const book_Passportal: Theme = {
  title: "Passportal",
  beach: "/assets/backgrounds/Passportal_front_cover_beach.png",
  coral: "/assets/backgrounds/Passportal_front_cover_coral.png",
  mint: "/assets/backgrounds/Passportal_front_cover_mint.png",
  ocean: "/assets/backgrounds/Passportal_front_cover_ocean.png",
  purple: "/assets/backgrounds/Passportal_front_cover_purple.png",
  rose: "/assets/backgrounds/Passportal_front_cover_rose.png",
  sun: "/assets/backgrounds/Passportal_front_cover_sun.png",
  default: "/assets/backgrounds/Passportal_front_cover_purple.png",
};

export const allBackgrounds: Theme[] = [
  backgroundImage_listen,
  backgroundImage_notes,
  backgroundImage_photos,
  backgroundImage_reader,
  backgroundImage_settings,
  book_LoveDrunk,
  book_MyExternalCause,
  book_Passportal,
];

export const austriaAlbum: string[] = [
  `${serverURL}/assets/photosAlbums/austria/austria001.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria002.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria003.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria004.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria005.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria006.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria007.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria008.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria009.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria010.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria011.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria012.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria013.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria014.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria015.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria016.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria017.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria018.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria019.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria020.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria021.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria022.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria023.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria024.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria025.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria026.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria027.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria028.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria029.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria030.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria031.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria032.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria033.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria034.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria035.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria036.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria037.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria038.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria039.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria040.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria041.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria042.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria043.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria044.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria045.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria046.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria047.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria048.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria049.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria050.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria051.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria052.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria053.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria054.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria055.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria056.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria057.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria058.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria059.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria060.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria061.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria062.jpg`,
  `${serverURL}/assets/photosAlbums/austria/austria063.jpg`,
];

export const parisAlbum: string[] = [
  `${serverURL}/assets/photosAlbums/paris/paris001.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris002.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris003.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris004.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris005.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris006.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris007.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris008.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris009.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris010.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris011.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris012.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris013.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris014.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris015.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris016.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris017.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris018.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris019.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris020.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris021.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris022.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris023.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris024.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris025.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris026.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris027.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris028.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris029.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris030.jpg`,
  `${serverURL}/assets/photosAlbums/paris/paris031.jpg`,
];

export const portugalAlbum: string[] = [
  `${serverURL}/assets/photosAlbums/portugal/portugal001.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal002.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal003.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal004.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal005.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal006.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal007.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal008.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal009.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal010.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal011.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal012.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal013.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal014.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal015.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal016.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal017.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal018.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal019.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal020.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal021.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal022.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal023.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal024.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal025.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal026.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal027.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal028.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal029.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal030.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal031.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal032.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal033.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal034.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal035.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal036.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal037.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal038.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal039.jpg`,
  `${serverURL}/assets/photosAlbums/portugal/portugal040.jpg`,
];

export const portugalPhotoshootAlbum: string[] = [
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot001.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot002.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot003.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot004.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot005.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot006.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot007.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot008.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot009.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot010.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot011.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot012.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot013.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot014.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot015.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot016.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot017.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot018.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot019.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot020.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot021.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot022.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot023.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot024.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot025.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot026.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot027.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot028.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot029.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot030.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot031.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot032.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot033.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot034.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot035.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot036.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot037.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot038.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot039.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot040.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot041.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot042.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot043.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot044.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot045.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot046.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot047.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot048.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot049.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot050.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot051.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot052.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot053.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot054.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot055.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot056.jpg`,
  `${serverURL}/assets/photosAlbums/portugalPhotoshoot/portugalPhotoshoot057.jpg`,
];

export const audioMyExternalCause: string[] = [
  `${serverURL}/assets/audio/myExternalCause_audio/000_introduction.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/001_anatomy_of_everything.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/002_my_love.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/003_my_happiness.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/004_my_strength.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/005_my_inspiration_and_my_motivation.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/006_my_peace.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/007_my_home.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/008_where_are_they_going_where_are_we_going.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/009_I_want_everything_with_you.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/outro_part_1.m4a`,
  `${serverURL}/assets/audio/myExternalCause_audio/outro_part_2.m4a`,
];

export interface AudioObject {
  [key: string]: string;
}

export const audioObjMyExternalCause: AudioObject = {
  introduction: `${serverURL}/assets/audio/myExternalCause_audio/000_introduction.m4a`,
  anatomy_of_everything: `${serverURL}/assets/audio/myExternalCause_audio/001_anatomy_of_everything.m4a`,
  my_love: `${serverURL}/assets/audio/myExternalCause_audio/002_my_love.m4a`,
  my_happiness: `${serverURL}/assets/audio/myExternalCause_audio/003_my_happiness.m4a`,
  my_strength: `${serverURL}/assets/audio/myExternalCause_audio/004_my_strength.m4a`,
  my_inspiration_and_my_motivation: `${serverURL}/assets/audio/myExternalCause_audio/005_my_inspiration_and_my_motivation.m4a`,
  my_peace: `${serverURL}/assets/audio/myExternalCause_audio/006_my_peace.m4a`,
  my_home: `${serverURL}/assets/audio/myExternalCause_audio/007_my_home.m4a`,
  where_are_they_going: `${serverURL}/assets/audio/myExternalCause_audio/008_where_are_they_going_where_are_we_going.m4a`,
  i_want_everything_with_you: `${serverURL}/assets/audio/myExternalCause_audio/009_I_want_everything_with_you.m4a`,
  outro_part_1: `${serverURL}/assets/audio/myExternalCause_audio/outro_part_1.m4a`,
  outro_part_2: `${serverURL}/assets/audio/myExternalCause_audio/outro_part_2.m4a`,
};
